# -*- coding: utf-8 -*-
"""Honey production in USA(1998-2021).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-3HviogwjSrJIvQtiCkqz6huf-jBdpp0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""### Information about data set
state: Various states of the U.S.

numcol: Number of honey-producing colonies.Honey producing colonies are the maximum number of colonies from which honey was taken during the year It is possible to take honey from colonies that did not survive the entire year.

yieldpercol : Honey yield per colony. Unit is pounds

totalprod: Total production (numcol x yieldpercol)Unit is pounds.

stocks: Refers to stocks held by producers. Unit is pounds

priceperlb: Refers to average price per pound based on expanded sales The unit is dollars.

prodvalue: Value of production (total prod x price per lb).The unit is dollars.

year: Year of production
"""

df=pd.read_csv(r"C:\Users\avani\Downloads\honeyproduction 1998-2021 (2).csv")
df.head()  # loading csv file into pandas dataframe

df.head() # finding first five values from dataset

df.tail()  # finding last five values from dataset

df.duplicated().sum()  # no duplicate values

df.isna().sum()    # no null values found

df.dtypes # finding data types

df.info()
# Information about Dataframe

df.shape  # finding shape of dataset (rows = 985 and columns =8)

df.describe()  # statistical info. about data

sns.pairplot(df,kind='kde')
plt.show()  # using pair plot

corr=df.corr()  #finding correlation
corr

plt.figure(figsize=(10,5))
sns.heatmap(corr,annot=True,cmap='Blues')  # plotting heatmap to show correlation of the data
plt.show()

"""## Q1 - 1.How has honey production yield changed from1998 to 2021 ?"""

plt.figure(figsize=(12,8))
sns.pointplot(x='year',y='totalprod',data=df,ci=None)
plt.title("Honey production yield changed from 1998 to 2021",size=18)
plt.xlabel("Year",size=15,color="blue")
plt.ylabel("Honey Production yield (Pounds)",size=15,color="blue")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12,8))
plt.scatter(df['year'],df['totalprod'])
plt.title('production vs year',fontsize=20,color='b')
plt.xlabel('year',fontsize=15,color='r')
plt.ylabel('total_ production',fontsize=15,color='r')
plt.xticks(rotation=90)
plt.show()

"""In this first question ,Honey production yield changes with the year. in which first some month honey production decreases after in between 2008 and 2009 honey production increases and after some year honey production again decreases.

# Q2- Over time,what are the major production trends across the states?
"""

sns.set_style('darkgrid')
sns.set(rc={'figure.figsize':(18,7)})
sns.set_context('paper',font_scale=1.5,rc={'grid.linewidth':0.5})
ax=sns.pointplot(data=df,x='year',y='totalprod',hue='State',ci=None)
ax.set_ylabel("Total Production")
ax.set_title("Production trends across the states ",size=20)
plt.xticks(rotation=90)
plt.legend(bbox_to_anchor=(1,1))
plt.show()

plt.figure(figsize=(20,10))  #setting figure size
sns.catplot(data=df,x='year', y='totalprod', col='State', kind='strip',height=3,col_wrap=5)  #using catplot for accurate visualization of the production trends across the state
plt.show() # showing the plot

"""In this Second question ,Total Production changes with each states per year as shown above graph.
1. Country like North Dakota keeps rising its productio trend with the passage of time , it keeps rising from 1998 to 2021.

2. Countries like California , Florida , South Dakota , Montana , Minnesota also have a higher production with the changes in the year but less than North Dakota.

3. Countries likeArkansas , Wisconsin , Texas , New York , Michigan also have a positive impact but not that too much.

4. other countries have zero impact , their production level remains same with the passage of time .

## Q3 -Does the data show any trends in terms of the number of honey producing colonies and yieldpercolony before 2006,which was when concern over Colony Collapse Disorder spread nationwide.
"""

df_year=(df[(df['year']<2006)] )
df_year

df2=df_year.groupby(['year'])[['yieldpercol','numcol']].sum().reset_index()
df2

sea2=sns.FacetGrid(df_year,col='year')
sea2.map(sns.scatterplot,'yieldpercol','numcol')
plt.show()

plt.plot(df2['year'],df2['yieldpercol'],color='blue')
plt.plot(df2['year'],df2['numcol'],color='maroon',lw=3,marker='o')
plt.xlabel('Year',color='blue')
plt.ylabel('Number of colony',color='blue')
plt.title('year wise yield per colony and number of colony',color='blue',size=21)
plt.show()

fig, (ax1,ax2) = plt.subplots(1,2,figsize=(14,5))  # nrows = 1, ncols =2
# ax1 is the name of plot1
# ax2 is the name of plot2

ax1.bar(df['year'],df['numcol'],color='orange',edgecolor='black')
ax1.set_title('Total honey production every Year')
ax1.set_ylabel('Sum of total production')
ax1.set_xlabel('Year')


ax2.bar(df['year'],df['yieldpercol'],color='blue')
ax2.set_title(' Total honey production value every Year')
ax2.set_xlabel('Year')
ax2.set_ylabel('Total production value')
ax2.grid()

plt.show()

"""In Q3, we can show that how total production and production value changes with year.

# Q4- Are there any patterns that can be observed between total honey production and value of production every year?
"""

sns.set(rc={'figure.figsize':(10,5)})
sns.scatterplot(data=df,x='totalprod',y='prodvalue',hue='year')
plt.show()

df1=df.groupby(['year']).sum()
df1.head()

fig, (ax1,ax2) = plt.subplots(1,2,figsize=(14,5))  # nrows = 1, ncols =2
# ax1 is the name of plot1
# ax2 is the name of plot2

ax1.bar(df1.index,df1['totalprod'],color='orange',edgecolor='black')
ax1.set_title('Sum of total honey production every Year')
ax1.set_ylabel('Sum of total production')
ax1.set_xlabel('Year')


ax2.plot(df1.index,df1['prodvalue'],color='blue',marker='d',markersize=8)
ax2.set_title(' Total honey production value every Year')
ax2.set_xlabel('Year')
ax2.set_ylabel('sum of production value')
ax2.grid()

plt.show()

"""In this Q4,Total honey production is decreasing with year but total produxtion value increasing with year, at 2015 its value is maximum after it decreas it and start increasing again.

# Q5- How has the value of production ,which in some sense could be tied to demand,changed every year?
"""

df1=df.groupby(['year'])[['totalprod','stocks','numcol','yieldpercol','prodvalue']].sum().reset_index()
df1.head()

df1['consumption']=df1['totalprod'] - df1['stocks']
df1.head()

sns.set(rc={'figure.figsize':(10,5)})
sns.set_style('whitegrid')
sns.set_context('poster',font_scale=0.5,rc={'grid.linewidth':0.7})
sns.set_palette('Purples_r')
sns.lineplot(data=df1,x='year',y='prodvalue',marker='o',ci=None)
sns.lineplot(data=df1,x='year',y='consumption',marker='>',ci=None)
plt.xlabel('year',size=12)
plt.ylabel('values for production and consumption',size=12)
plt.xticks(df1['year'],rotation=45)
plt.title('production value tied up with demand year wise',color='black',size=18)
plt.show()

"""In this Q5 , we can clearly show that when consumption increases then product value also increases.and In 2014 the production value reaches its maximum point which leads to increase the demand to its maximum limit.

## Q6-Constructs the related plots using Seaborn and Matplot apply customization and derive insights from the visualization

here in this graph we can clearly show that production with state. so we can take astimates that which state produce more honey production and and which states produce less honey production.
"""

plt.figure(figsize=(30,30))
sns.barplot(x='totalprod',y='State',data=df.sort_values("totalprod",ascending=False),label='production per state',color='blue')
sns.barplot(x='stocks',y='State',data=df.sort_values("totalprod",ascending=False),label='stocks per state',color='pink')
plt.legend(ncol=2)
plt.title("Honey production vs state",size=28)
plt.show()

df_sorted=df.sort_values(['totalprod','stocks'])

plt.figure(figsize=(40,15))
plt.bar(df_sorted['State'],df_sorted['totalprod'],color='cyan',label='totalproduction per state')
plt.bar(df_sorted['State'],df_sorted['stocks'],color='orange',label='totalproduction per stocks',bottom=df_sorted['totalprod'])
# plt.legend(ncol=2)
plt.title('State wise report of production',size=45)
plt.xlabel('State',size=25)
plt.ylabel('Total prod and stocks',size=25)
plt.xticks(rotation=45)
plt.grid()
plt.show()

maxp=df.groupby(['year'])['totalprod'].sum()
df_sorted=df.sort_values(['totalprod']).sum()
r2=maxp.head()
r2

plt.figure(figsize=(5,5))
plt.pie(x = r2.values,labels=r2.index,
        colors=['yellow','blue','red','green','cyan'],autopct='%.3f%%',
       explode=(0,0,0.1,0,0),shadow=True,counterclock=False)
plt.title(' Top 5 Year of  Total Honey Production',fontsize=15,color='blue')
plt.show()

"""In this above pie chart shows that honey producation max in 2000 ."""

fig, axes = plt.subplots(2, 3, figsize=(25, 15))

fig.suptitle('US Honey Production 1995-2021 - distribution of variables', fontsize='xx-large', y=0.93)

sns.histplot(ax=axes[0, 0], data=df, x='numcol')
sns.histplot(ax=axes[0, 1], data=df, x='yieldpercol')
sns.histplot(ax=axes[0, 2], data=df, x='totalprod')
sns.histplot(ax=axes[1, 0], data=df, x='stocks')
sns.histplot(ax=axes[1, 1], data=df, x='prodvalue')
sns.histplot(ax=axes[1, 2], data=df, x='priceperlb')

"""Based on these charts we can say that:

all of the graph are right skewed insted of yield per colony.
1. NORTH DAKOTA IS A STATE WHICH HAVE A HIGHEST PRODUCTION AND AGREAT AMOUNT OF STOCKS LEFT.
2. SOUTH DAKOTA IS THE STATE WHICH HAVE THE HIGHEST AMOUNT OF STOCK LEFT.
3. OKLAHOMA IS A STATE WHICH HAVE NO STOCKS LEFT AND HAVE THE LOWEST TOTAL PRODUCTION.


"""







